# Generated by Django 5.1.3 on 2024-12-04 19:07

import account.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_person_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_picture',
            field=models.ImageField(default='images/profiles/defaultProfilePicture.png', upload_to='images/profiles', validators=[account.validators.validate_file_size]),
        ),
    ]
